#!/usr/bin/env bash

# Desktops
bspc monitor -d 1 2 3 4 5 6 7 8 9 0

# Fix Java: Cambiar el nombre del Window Manager 
wmname LG3D &

# Basic rules
bspc config border_width 1
bspc config window_gap 8
bspc config split_ratio 0.52
bspc config focus_follows_pointer false

# Set wallpaper
feh --bg-fill ~/.config/wallpaper/pic.jpg &

# Vmware user agent
vmware-user-suid-wrapper >/dev/null &

# Launch picom
picom >/dev/null &

# Launch polybar
~/.config/polybar/./launch.sh

# Launch sxhkd
pgrep -x sxhkd >/dev/null || sxhkd &